DROP SCHEMA IF EXISTS AntiMess;

CREATE SCHEMA AntiMess DEFAULT CHARACTER SET utf8;

USE AntiMess;

CREATE TABLE Lagerort
(
    Container VARCHAR(255),
	LagerortID INT AUTO_INCREMENT,
    PRIMARY KEY (LagerortID)
);

CREATE TABLE Benutzer
(
    BenutzerName VARCHAR (255),
    Password VARCHAR(255),
    UserID INT AUTO_INCREMENT,
    PRIMARY KEY (UserID)
);

CREATE TABLE Gegenstand
(
    GegenstandName VARCHAR(255) NOT NULL,
    Lagerdatum DATE,
    Icon VARCHAR(255),
	LagerortID_FK INT,
    UserID_FK INT,
	GegenstandID INT AUTO_INCREMENT,
    FOREIGN KEY (LagerortID_FK) REFERENCES Lagerort(LagerortID),
    FOREIGN KEY (UserID_FK) REFERENCES Benutzer(UserID) ON DELETE SET NULL,
	PRIMARY KEY (GegenstandID)
);

CREATE TABLE USER_LAGERORT
(
    LagerortID_FK INT,
	UserID_FK INT,
    FOREIGN KEY (LagerortID_FK) REFERENCES Lagerort(LagerortID),
    FOREIGN KEY (UserID_FK) REFERENCES Benutzer(UserID) ON DELETE SET NULL
);

CREATE TABLE Adresse
(
	Straße VARCHAR(255),
    hausnummer INT NOT NULL,
    Postleitzahl INT NOT NULL,
    ORT VARCHAR(255)
);

ALTER TABLE Gegenstand DROP FOREIGN KEY gegenstand_ibfk_2;
ALTER TABLE Gegenstand DROP UserID_FK;
ALTER TABLE Gegenstand ADD BenutzerNameFK VARCHAR(255);

ALTER TABLE USER_LAGERORT DROP FOREIGN KEY user_lagerort_ibfk_2;
ALTER TABLE USER_LAGERORT DROP UserID_FK;
ALTER TABLE USER_LAGERORT ADD BenutzerName_FK VARCHAR(255);

ALTER TABLE Benutzer MODIFY UserID INT NOT NULL;
ALTER TABLE Benutzer DROP PRIMARY KEY;
ALTER TABLE Benutzer DROP UserID;
ALTER TABLE Benutzer CHANGE BenutzerName BenutzerName VARCHAR(255) PRIMARY KEY;
ALTER TABLE Benutzer ADD SessionID INT DEFAULT NULL;

ALTER TABLE Gegenstand ADD FOREIGN KEY (BenutzerNameFK) REFERENCES Benutzer(BenutzerName) ON DELETE SET NULL;
ALTER TABLE USER_LAGERORT ADD FOREIGN KEY (BenutzerName_FK) REFERENCES Benutzer(BenutzerName) ON DELETE SET NULL;

CREATE TABLE Aktive_Session
(
	Session_ID VARCHAR(255) DEFAULT NULL,
    BenutzerName_FK VARCHAR(255),
    FOREIGN KEY (BenutzerName_FK) REFERENCES Benutzer(BenutzerName) ON DELETE SET NULL
);

